#pragma once

#define SCREEN_WIDTH_START 320
#define SCREEN_HEIGHT_START 240

//#define SCREEN_WIDTH_START 640
//#define SCREEN_HEIGHT_START 360

//#define SCREEN_WIDTH_START 480
//#define SCREEN_HEIGHT_START 270

//#define SCREEN_WIDTH_START 1600
//#define SCREEN_HEIGHT_START 900